/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Rosemberg
 */
public class FormSelect_Color extends javax.swing.JFrame {
private Integer val=null;
private FormInicio myJuego;
private int jugador;
    /**
     * Creates new form FormSelect_Color
     */
    public FormSelect_Color(Integer val2,FormInicio myJuego, int val) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.myJuego=myJuego;
        
        this.jugador=val;
        
        if(val2!=null)
        this.deshabilitar(val2);
        
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMoneda = new javax.swing.JLabel();
        slsMoneda1 = new javax.swing.JRadioButton();
        lblMoneda1 = new javax.swing.JLabel();
        slsMoneda2 = new javax.swing.JRadioButton();
        lblMoneda2 = new javax.swing.JLabel();
        slsMoneda3 = new javax.swing.JRadioButton();
        lblMoneda3 = new javax.swing.JLabel();
        slsMoneda4 = new javax.swing.JRadioButton();
        lblMoneda4 = new javax.swing.JLabel();
        slsMoneda5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccion de Color");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/Imagenes/50.png"))); // NOI18N

        slsMoneda1.setBackground(new java.awt.Color(255, 255, 255));
        slsMoneda1.setText("Moneda de 50 Pesos");
        slsMoneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slsMoneda1ActionPerformed(evt);
            }
        });

        lblMoneda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/Imagenes/100.png"))); // NOI18N

        slsMoneda2.setBackground(new java.awt.Color(255, 255, 255));
        slsMoneda2.setText("Moneda de 100 Pesos");
        slsMoneda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slsMoneda2ActionPerformed(evt);
            }
        });

        lblMoneda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/Imagenes/200.png"))); // NOI18N

        slsMoneda3.setBackground(new java.awt.Color(255, 255, 255));
        slsMoneda3.setText("Moneda de 200 Pesos");
        slsMoneda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slsMoneda3ActionPerformed(evt);
            }
        });

        lblMoneda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/Imagenes/500.png"))); // NOI18N

        slsMoneda4.setBackground(new java.awt.Color(255, 255, 255));
        slsMoneda4.setText("Moneda de 500 Pesos");
        slsMoneda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slsMoneda4ActionPerformed(evt);
            }
        });

        lblMoneda4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/Imagenes/1000.png"))); // NOI18N

        slsMoneda5.setBackground(new java.awt.Color(255, 255, 255));
        slsMoneda5.setText("Moneda de 1000 Pesos");
        slsMoneda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slsMoneda5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione la Ficha para Jugar");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/Imagenes/barra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMoneda4)
                                .addGap(18, 18, 18)
                                .addComponent(slsMoneda5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMoneda3)
                                .addGap(18, 18, 18)
                                .addComponent(slsMoneda4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMoneda2)
                                .addGap(18, 18, 18)
                                .addComponent(slsMoneda3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMoneda)
                                .addGap(18, 18, 18)
                                .addComponent(slsMoneda1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMoneda1)
                                .addGap(18, 18, 18)
                                .addComponent(slsMoneda2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoneda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(slsMoneda1)
                        .addGap(9, 9, 9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoneda1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(slsMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMoneda2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(slsMoneda3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoneda3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(slsMoneda4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoneda4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(slsMoneda5)))
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slsMoneda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slsMoneda4ActionPerformed
        // TODO add your handling code here:
        val=4;
        this.slsMoneda2.setSelected(false);
        this.slsMoneda3.setSelected(false);
        this.slsMoneda1.setSelected(false);
        this.slsMoneda5.setSelected(false);
    }//GEN-LAST:event_slsMoneda4ActionPerformed

    private void slsMoneda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slsMoneda5ActionPerformed
        // TODO add your handling code here:
        val=5;
        this.slsMoneda2.setSelected(false);
        this.slsMoneda3.setSelected(false);
        this.slsMoneda4.setSelected(false);
        this.slsMoneda1.setSelected(false);
    }//GEN-LAST:event_slsMoneda5ActionPerformed

    private void slsMoneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slsMoneda1ActionPerformed
        // TODO add your handling code here:
        val=1;
        this.slsMoneda2.setSelected(false);
        this.slsMoneda3.setSelected(false);
        this.slsMoneda4.setSelected(false);
        this.slsMoneda5.setSelected(false);
    }//GEN-LAST:event_slsMoneda1ActionPerformed

    private void slsMoneda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slsMoneda2ActionPerformed
        // TODO add your handling code here:
        val=2;
        this.slsMoneda1.setSelected(false);
        this.slsMoneda3.setSelected(false);
        this.slsMoneda4.setSelected(false);
        this.slsMoneda5.setSelected(false);
    }//GEN-LAST:event_slsMoneda2ActionPerformed

    private void slsMoneda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slsMoneda3ActionPerformed
        // TODO add your handling code here:
        val=3;
        this.slsMoneda2.setSelected(false);
        this.slsMoneda1.setSelected(false);
        this.slsMoneda4.setSelected(false);
        this.slsMoneda5.setSelected(false);
    }//GEN-LAST:event_slsMoneda3ActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.val==null)
        {
            
            JOptionPane.showMessageDialog(rootPane, "Seleccione una Opcion");
            return;
        }
        
        if(this.jugador==1)
        this.myJuego.setBoton1(val);
        
        if(this.jugador==2)
        this.myJuego.setBoton2(val);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deshabilitar(Integer val){
       
        if(val==1){
        this.lblMoneda.setEnabled(false);
        this.slsMoneda1.setEnabled(false);
        }
        
        if(val==2){
        this.lblMoneda1.setEnabled(false);
        this.slsMoneda2.setEnabled(false);
        }
        
        if(val==3){
        this.lblMoneda2.setEnabled(false);
        this.slsMoneda3.setEnabled(false);
        }
        
        if(val==4){
        this.lblMoneda3.setEnabled(false);
        this.slsMoneda4.setEnabled(false);
        }
        
        if(val==5){
        this.lblMoneda4.setEnabled(false);
        this.slsMoneda5.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblMoneda1;
    private javax.swing.JLabel lblMoneda2;
    private javax.swing.JLabel lblMoneda3;
    private javax.swing.JLabel lblMoneda4;
    private javax.swing.JRadioButton slsMoneda1;
    private javax.swing.JRadioButton slsMoneda2;
    private javax.swing.JRadioButton slsMoneda3;
    private javax.swing.JRadioButton slsMoneda4;
    private javax.swing.JRadioButton slsMoneda5;
    // End of variables declaration//GEN-END:variables
}
